#page title
page_title                                : Banana Browser

# App Info
ios_app_id                                :
appstore_link                             :
playstore_link                            : https://play.google.com/store/apps/details?id=org.triple.banana
presskit_download_link                    :
app_icon                                  : /assets/app_icon.svg
app_name                                  : Banana Browser
app_price                                 : Safer, faster, and more stable
app_description                           : Banana Browser is a fast, easy to use, secure browser based on the world's most widely used Chromium. It brings you various extended features such as Adblock, Privacy Protection, and so on.
enable_smart_app_banner                   : true



# Information About Yourself
your_name                                 : Banana team
your_link                                 : https://triplebanana.dev
your_city                                 : Austria
email_address                             : org.triple.banana@gmail.com
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Adblock
    description                           : We have a built-in Ad Blocker. It blocks ads on sites that show intrusive or misleading ads.
    fontawesome_icon_name                 : ban
    
  - title                                 : Secure DNS over HTTP(S)
    description                           : We support a built-in Secure DNS. You can bypass website blocks using Secure DNS over HTTPS.
    fontawesome_icon_name                 : user-secret

  - title                                 : Secure Login
    description                           : We support a secure login using additional authentication(e.g. Fingerprint, Pattern, PIN and so on) on web sites.
    fontawesome_icon_name                 : sign-in-alt

  - title                                 : Dark Mode
    description                           : We have a built-in Dark Mode. You can easily switch the UI and web pages to a dark theme with one click.
    fontawesome_icon_name                 : moon

  - title                                 : Toolbar Editor
    description                           : You can personalize your browsing experience rearranging frequently used buttons on the bottom toolbar.
    fontawesome_icon_name                 : grip-horizontal
  
  - title                                 : Data Saving Mode
    description                           : We have a built-in data saving mode to reduce mobile data. It loads pages faster and use up to 60% less data.
    fontawesome_icon_name                 : wifi

  - title                                 : External Download Manager
    description                           : We support external download manager such as IDM / ADM as well as built-in download manager.
    fontawesome_icon_name                 : download

  - title                                 : Extended Media Player
    description                           : We have built-in powerful extend media player(e.g. PIP mode) for video elements on fullscreen mode.
    fontawesome_icon_name                 : play-circle

  - title                                 : Browser Lock
    description                           : When opening our Banana Browser, you can use additional authentications to protect your personal data securely.
    fontawesome_icon_name                 : lock

  - title                                 : Privacy & Security
    description                           : Protect your privacy online with strong security features provided by Banana Browser
    fontawesome_icon_name                 : shield-alt



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffdc14"
feature_icons_background_color            : "#571cce"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
